id = "kyoz-snippets"
name = "Kyoz Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Erick Palomino <kyoz.dev@gmail.com>"]
description = "Snippets personales"
repository = "https://github.com/tu-usuario/kyoz-snippets"

snippets = [
  "./snippets/typescript.json",
  "./snippets/svelte.json",
  "./snippets/json.json",
  "./snippets/css.json",
  "./snippets/yaml.json",
  "./snippets/markdown.json"
]
